name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on semantic version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        
    - name: Install dependencies
      run: make deps
      
    - name: Build all binaries
      run: make build-all
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bin/nitpick-linux-amd64
          bin/nitpick-linux-arm64
          bin/nitpick-linux-arm
          bin/nitpick-darwin-amd64
          bin/nitpick-darwin-arm64
          bin/nitpick-windows-amd64.exe
          bin/nitpick-windows-arm64.exe
        generate_release_notes: true
        draft: false
        prerelease: false 
